Improve install_cargo_packages
Fix #7

diff --git a/private_dot_local/bin/executable_install_cargo_packages b/private_dot_local/bin/executable_install_cargo_packages
--- a/private_dot_local/bin/executable_install_cargo_packages
+++ b/private_dot_local/bin/executable_install_cargo_packages
@@ -1,8 +1,14 @@
 #!/bin/bash
 
+function existsCmd () {
+    type -a $1 > /dev/null 2>&1
+}
+
 while read -r line
 do
-    cargo install $line
-    sleep 3
+    if ! existsCmd $line; then
+        echo "$line is not found"
+        cargo install $line
+    fi
 done < ~/cargo_packages.txt
 
