Update vup

diff --git a/private_dot_local/bin/executable_vup b/private_dot_local/bin/executable_vup
--- a/private_dot_local/bin/executable_vup
+++ b/private_dot_local/bin/executable_vup
@@ -48,6 +48,14 @@ before_sudo() {
   fi
 }
 
+# brew upgrade commands
+brew_update_process() {
+  brew update
+  brew upgrade
+  brew upgrade --cask
+  brew cleanup
+}
+
 # Ubuntu
 ubuntu() {
   # Upgrade APT repogitory list
@@ -59,6 +67,10 @@ ubuntu() {
   sudo apt-get clean
   # Upgrade snaps
   sudo snap refresh
+  which brew >/dev/null
+  if test $? -eq 0; then
+    brew_update_process
+  fi
 }
 
 # Arch Linux
@@ -69,10 +81,7 @@ arch() {
 
 # Mac
 mac() {
-  brew update
-  brew upgrade
-  brew upgrade --cask
-  brew cleanup
+  brew_update_process
 }
 
 update_asdf_tools() {
@@ -82,8 +91,7 @@ update_asdf_tools() {
 }
 
 update_asdf_nodejs_lts() {
-  asdf uninstall nodejs lts
-  asdf install nodejs lts
+  asdf install nodejs "$(asdf nodejs resolve lts --latest-available)"
 }
 
 # other
@@ -108,6 +116,8 @@ ohter_tools() {
   tldr --update
   # GitHub CLI extensions update
   gh extensions upgrade --all
+  # flyctl upgrade
+  flyctl version upgrade
   # Upgrade fisher
   fish -c 'fisher update'
   asdf plugin update --all
@@ -158,6 +168,9 @@ ohter_tools
 
 # ファイルがあれば再起動を促す
 if test -e /var/run/reboot-required; then
-  echo "\"/var/run/reboot-required\" exists. Reboot the system?(recommend)"
-  re_boot
+  # WSL かチェックする
+  if test ! -e /proc/sys/fs/binfmt_misc/WSLInterop; then
+    echo "\"/var/run/reboot-required\" exists. Reboot the system?(recommend)"
+    re_boot
+  fi
 fi
